In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
"microsoft/Phi-3-mini-4k-instruct",
torch_dtype="auto"
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

In [2]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model = model,
    tokenizer = tokenizer,
    return_full_text = False,
    max_new_tokens = 500,
    do_sample = False
)

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

In [4]:
prompt = """Write an email apologizing to Sarah for the tragic gardening mishap. 
Explain how it happened.<|assistant|>"""

In [5]:
input_ids = tokenizer(prompt, return_tensors='pt').input_ids

In [9]:
generation_output = model.generate(
    input_ids = input_ids,
    max_new_tokens = 70
)

print(tokenizer.decode(generation_output[0]))

Write an email apologizing to Sarah for the tragic gardening mishap.
Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap

Dear Sarah,

I hope this email finds you well. I am writing to express my deepest apologies for the unfortunate incident that occurred in your garden. I understand that it must have been a devastating experience for you, and I

In [10]:
generation_output[0]

tensor([14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
          293, 16423,   292,   286,   728,   481, 29889, 29871,    13,  9544,
         7420,   920,   372,  9559, 29889, 32001,  3323,   622, 29901,   317,
         3742,   406,  6225, 11763,   363,   278, 19906,   292,   341,   728,
          481,    13,    13, 29928,   799, 19235, 29892,    13,    13, 29902,
         4966,   445,  4876, 14061,   366,  1532, 29889,   306,   626,  5007,
          304,  4653,   590,  6483,   342,  3095, 11763,   363,   278,   443,
         6477,   403, 15134,   393, 10761,   297,   596, 16423, 29889,   306,
         2274,   393,   372,  1818,   505,  1063,   263,  2906,   579,  1218,
         7271,   363,   366, 29892,   322,   306])

In [14]:
for id in input_ids[0]:
    print(f"ID: {id}, Word: {tokenizer.decode(id)}")

ID: 14350, Word: Write
ID: 385, Word: an
ID: 4876, Word: email
ID: 27746, Word: apolog
ID: 5281, Word: izing
ID: 304, Word: to
ID: 19235, Word: Sarah
ID: 363, Word: for
ID: 278, Word: the
ID: 25305, Word: trag
ID: 293, Word: ic
ID: 16423, Word: garden
ID: 292, Word: ing
ID: 286, Word: m
ID: 728, Word: ish
ID: 481, Word: ap
ID: 29889, Word: .
ID: 29871, Word:
ID: 13, Word:

ID: 9544, Word: Exp
ID: 7420, Word: lain
ID: 920, Word: how
ID: 372, Word: it
ID: 9559, Word: happened
ID: 29889, Word: .
ID: 32001, Word: <|assistant|>

In [15]:
print(tokenizer.decode(3323))
print(tokenizer.decode(622))
print(tokenizer.decode([3323, 622]))
print(tokenizer.decode(29901))

Sub
ject
Subject
:

In [1]:
text = """
English and CAPITALIZATION
🎵鸟
show_tokens False None elif == >= else: two tabs:" " Three tabs: " "
12.0*50=600
"""

In [7]:
colors_list = [
 '102;194;165', '252;141;98', '141;160;203',
 '231;138;195', '166;216;84', '255;217;47'
]

In [5]:
from transformers import AutoTokenizer

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) + '\x1b[0m', end=' '
        )

In [6]:
show_tokens(text, "google-bert/bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

c:\Users\Jitto\Documents\Code\hands-on-llm-book\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Jitto\.cache\huggingface\hub\models--google-bert--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

[CLS] english and capital ##ization [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP]

In [8]:
tokenizer.decode([8582, 236,
113])

NameError: name 'tokenizer' is not defined

In [9]:
## Recommendation model

In [10]:
import pandas as pd
from urllib import request

data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

In [11]:
lines = data.read().decode("utf-8").split('\n')[2:]

In [14]:
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

In [16]:
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [17]:
songs_df.head()

                                                title      artist
id
0                        Gucci Time (w\/ Swizz Beatz)  Gucci Mane
1   Aston Martin Music (w\/ Drake & Chrisette Mich...   Rick Ross
2                       Get Back Up (w\/ Chris Brown)        T.I.
3                  Hot Toddy (w\/ Jay-Z & Ester Dean)       Usher
4                                        Whip My Hair      Willow

In [18]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43']

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118', '119', '120', '121', '122', '123', '50', '70', '71', '124', '17', '85', '14', '82', '48', '125', '47', '46', '72', '53', '25', '73', '4', '126', '59', '74', '20', '43', '127', '128', '129', '13', '82', '48', '130', '131', '132', '133', '134', '135', '136', '137', '59', '46', '138', '43', '20', '139', '140', '73', '57', '70', '141', '3', '1', '74', '142', '143', '144', '145', '48', '13', '25', '146', '50', '147', '126', '59', '20', '148', '149', '150', '151', '152', '56', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '60', '176', '51', '177', '178', '179', '180', '181', '182', '183', '184', '185', '57', '186', '187', '188', '189', '190', '191', '46', '192', '193', '194', '195', '196', '197', '198', '25', '199', '200', '49', '201', '100', '202', '203', '204', '205', '206', '207', '32', '208', '209', '210']

In [19]:
from gensim.models import Word2Vec

model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [28]:
song_id = 2172
# Ask the model for songs similar to song #2172
(model.wv.most_similar(positive=str(song_id), topn=5))

[('2849', 0.9978342652320862),
 ('6624', 0.9975029230117798),
 ('3119', 0.9966464042663574),
 ('6658', 0.9964823722839355),
 ('3094', 0.9962052702903748)]

In [29]:
import numpy as np
def print_recommendations(song_id):
 similar_songs = np.array(
 model.wv.most_similar(positive=str(song_id),topn=5)
 )[:,0]
 return songs_df.iloc[similar_songs]
# Extract recommendations
print_recommendations(2172)

                               title        artist
id
2849                Run To The Hills   Iron Maiden
6624         Everybody Wants Some!!!     Van Halen
3119    There's Only One Way To Rock   Sammy Hagar
6658   (Bang Your Head) Metal Health    Quiet Riot
3094                Breaking The Law  Judas Priest